### ISSUE TITLE
Incorrect arguments passed  in a method in APIClient class

### ISSUE THREAD

**Issue by Gopinath-G01** [camunda-community-hub/camunda-engine-rest-client-java#1]
### **Description**
While trying to use the camunda-engine-rest-client-openapi-springboot to remotely interact with a camunda engine I am seeing below issue during the application startup

```
An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.camunda.community.rest.client.invoker.ApiClient.buildRequestBodyMultipart(ApiClient.java:1220)

The following method did not exist:

    okhttp3.RequestBody.create(Ljava/lang/String;Lokhttp3/MediaType;)Lokhttp3/RequestBody;
```

Issue seems to be in this line (#1220) of APIClient class, that was auto-generated as part of org.camunda.community.rest.client.invoker package. 

`mpBuilder.addPart(partHeaders, RequestBody.create(parameterToString(param.getValue()), null));`

Below is the actual signature of the RequestBody.create method

`RequestBody okhttp3.RequestBody.create(@Nullable MediaType contentType, String content)`

But in above class first a String argument was passed then a null value in place of the MediaType

### **Dependency Used in my application**
```
<dependency>
	<groupId>org.camunda.community</groupId>
	<artifactId>camunda-engine-rest-client-openapi-springboot</artifactId>
	<version>7.16.0-alpha1</version>
</dependency>
```

### **Remote Engine used:** 
camunda-bpm-run-7.13.0-alpha2 - with default configurations

**Application.Java:**
```
@SpringBootApplication
@ComponentScan(basePackages = "com")
public class Application implements CommandLineRunner{

	
	@Autowired
	StartProcessController startProcessController;
	public static void main(String... args) {
		SpringApplication.run(Application.class, args);
	}

	@Override
	public void run(String... args) throws Exception {
        System.out.println("Started Processing... : " + new Date());
        startProcessController.execute();
	}
}
```

**StartProcessController.java:**
```
@Component
public class StartProcessController {

	@Autowired
    private ProcessDefinitionApi processDefinitionApi;
	
	public void execute() {
		try {
			ProcessInstanceWithVariablesDto processInstance = processDefinitionApi.startProcessInstanceByKey(
			        "sample-process-solution-process",
			        new StartProcessInstanceDto());
			
			String processInstId = processInstance.getId();
			System.out.println("ProcessInstance instantiated with id: "+processInstId);
			
		} catch (ApiException e) {
			e.printStackTrace();
		}
	}
}
```

BPMN models referenced from [here](https://github.com/camunda-community-hub/camunda-platform-to-cloud-migration/tree/main/example/process-solution-camunda-platform/src/main/resources)

**Comment by filiprafaj** [comment]
I think, I've seen this error. Try adding: 
```
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <version>4.9.0</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

**Comment by Gopinath-G01** [comment]
That worked.! so the issue is indeed in the library and not in the client code
